### PR TITLE
#47 - HtmlTemplateBrick

### LINKED ISSUE #47: Codeless bricks
Simple bricks might not need JS code, something like this in the HTML templates:

    <div class="image-wrapper" data-aem-selector="picture"></div>

can mean "append all nodes matching the 'picture' CSS selector to this element.

Initially I think we'll still need an empty JS class in the brick folder, and that can also be useful it small bits of additional code are required.

### PR DESCRIPTION
**Pull request by bdelacretaz**
Fix #47 - work in progress, the hero CSS is somewhat broken at this point

Test URLs:
- Before: https://main--helix-website-wc--adobe-gw2023-project-bricks.hlx.page/
- After: https://codeless-bricks--helix-website-wc--adobe-gw2023-project-bricks.hlx.page/

### CODE REVIEW

**Comment by bdelacretaz** [comment]
From my point of view this would be ready, but the linter complains, need to fix a few details.

At commit 3ce3e8a this demonstrates a low-code HTML template, with one element populated from a `data-aem-selector` attribute, and another one populated with JS code.

The template uses shadowroot='false', CSS "isolation" is provided by prefixing rules with the name of our custom `aem-hero` element. I think that's good enough, no need for shadow DOM in this case.

**Comment by bdelacretaz** [comment]
> Could this be out of the box in the Brick class itself?

Ah maybe, if that doesn't make that class too complex. And I think it's good to make shadow DOM optional, as in many cases it's not needed.

Feel free to refactor, I'm still not a JS guru anyway ;-)

**Comment by fnhipster** [comment]
I think the shadow root as default got in when we initially used slots but that's not the case anymore. It might have simplified at lot if we didn't use it at all.

**Review by dicagno — APPROVED** [review]
nice! LGTM

**Pull request merged**
